# Generated by Django 6.0.2 on 2026-08-25 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('bridal', 'Bridal Couture'), ('arabic', 'Arabic & Floral'), ('indo_western', 'Indo-Western'), ('mandala', 'Mandala Art'), ('feet', 'Feet & Bridal Leg Art'), ('minimal', 'Minimalist & Finger')], default='bridal', max_length=50)),
                ('image_url', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='e.g. Dark Stain, Eucalyptus Oil, Sangeet', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('bridal', 'Bridal Couture'), ('arabic', 'Arabic & Floral'), ('indo_western', 'Indo-Western & Fusion'), ('mandala', 'Mandala & Minimalist'), ('party', 'Sangeet & Party Mehendi'), ('traditional', 'Traditional Rajasthani/Marwari')], default='bridal', max_length=50)),
                ('tagline', models.CharField(blank=True, help_text="Short highlight, e.g., 'Elaborate elbow-length bridal intricacy'", max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'Most Popular', 'Bridal Signature'", max_length=50)),
                ('image_url', models.CharField(blank=True, help_text='Image URL or static path', max_length=400)),
                ('features_list', models.TextField(blank=True, help_text='Enter features separated by commas or newlines')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('09:00 AM', '09:00 AM - 11:30 AM (Morning Slot)'), ('11:30 AM', '11:30 AM - 02:00 PM (Mid-Day Slot)'), ('02:00 PM', '02:00 PM - 04:30 PM (Afternoon Slot)'), ('04:30 PM', '04:30 PM - 07:00 PM (Evening Sunset Slot)'), ('07:00 PM', '07:00 PM - 09:30 PM (Night Gala Slot)')], max_length=20)),
                ('venue_type', models.CharField(choices=[('studio', 'Artist Luxury Studio (In-Salon)'), ('home', 'Client Venue / Home Visit (+ ₹500 Travel)')], default='studio', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full address for Home / Wedding Venue visit')),
                ('special_notes', models.TextField(blank=True, help_text='Custom bridal figures, special requests, number of hands, etc.')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.service')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_location', models.CharField(default='Mumbai, Maharashtra', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='booking.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('service_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='booking.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('booking_date', 'booking_time'), name='unique_active_slot_booking'),
        ),
    ]
