# Generated by Django 6.0.2 on 2026-08-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Aura Mehendi Artistry', max_length=150)),
                ('tagline', models.CharField(default='Haute Henna Atelier', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=25)),
                ('email', models.EmailField(default='bookings@auramehendi.com', max_length=254)),
                ('whatsapp', models.CharField(default='+919876543210', max_length=25)),
                ('instagram', models.CharField(default='@auramehendi', max_length=120)),
                ('address', models.TextField(default='Bandra West, Mumbai, Maharashtra 400050')),
                ('about', models.TextField(default='Exquisite bridal and contemporary henna artistry using 100% organic Rajasthani henna.')),
                ('mon_fri_hours', models.CharField(default='09:00 AM – 09:30 PM', max_length=50)),
                ('sat_hours', models.CharField(default='09:00 AM – 09:30 PM', max_length=50)),
                ('sun_hours', models.CharField(default='10:00 AM – 07:00 PM', max_length=50)),
            ],
            options={
                'verbose_name': 'Business Settings',
            },
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload design image', null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image (overrides image URL)', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive services won't appear on the public site"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('new_booking', 'New Booking'), ('cancellation', 'Booking Cancelled'), ('review', 'New Review'), ('reschedule', 'Booking Rescheduled'), ('status_change', 'Status Changed')], default='new_booking', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.booking')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('is_blocked', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='Artist Unavailable', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
